cd "wings-cafe-invetory-system\public\images\products"
ren "Bottled Water.jpg" "Bottled-Water.jpg"
ren "Bottled Water1.jpg" "Bottled-Water1.jpg"
ren "Energy Drink.jpg" "Energy-Drink.jpg"
ren "Energy Drink1.jpg" "Energy-Drink1.jpg"
ren "Liquid fruit.jpg" "Liquid-fruit.jpg"
ren "Liquid fruit1.jpg" "Liquid-fruit1.jpg"
ren "Potato Chips.jpg" "Potato-Chips.jpg"
ren "Potato Chips1.jpg" "Potato-Chips1.jpg"
ren "Fried fish.jpg" "Fried-fish.jpg"
ren "Fried fish1.jpg" "Fried-fish1.jpg"
